batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
batchs: 40, val_batches: 21
Traceback (most recent call last):
  File "lstm.py", line 107, in <module>
    metrics = lstm.run()
  File "/home/s2576597/DL_GROUP/networks.py", line 111, in run
    total_loss = self.train()
  File "/home/s2576597/DL_GROUP/networks.py", line 56, in train
    self.model.cuda()
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 116, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s2576597/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable


###############################################################################
Peregrine Cluster
Job 5946799 for user 's2576597'
Finished at: Tue May 21 11:29:18 CEST 2019

Job details:
============

Name                : run_lstm
User                : s2576597
Partition           : gpu
Nodes               : pg-gpu29
Cores               : 12
State               : FAILED
Submit              : 2019-05-21T11:27:27
Start               : 2019-05-21T11:28:44
End                 : 2019-05-21T11:29:18
Reserved walltime   : 23:55:00
Used walltime       : 00:00:34
Used CPU time       : 00:46:08 (efficiency: 678.46%)
% User (Computation): 39.14%
% System (I/O)      : 60.86%
Mem reserved        : 8G/node
Max Mem used        : 105.84M (pg-gpu29)
Max Disk Write      : 481.28K (pg-gpu29)
Max Disk Read       : 10.45G (pg-gpu29)


Acknowledgements:
=================

Please see this page if you want to acknowledge Peregrine in your publications:

https://redmine.hpc.rug.nl/redmine/projects/peregrine/wiki/ScientificOutput

################################################################################
